import { PermissionCategory, PermissionTemplate, RoleTemplate } from './permission-management-types';

// Default permission categories
export const DEFAULT_PERMISSION_CATEGORIES: PermissionCategory[] = [
  {
    id: 'user_management',
    name: 'User Management',
    nameBg: 'Управление на потребители',
    nameEn: 'User Management',
    description: 'Permissions related to user management',
    descriptionBg: 'Права, свързани с управлението на потребители',
    descriptionEn: 'Permissions related to user management',
    icon: 'Users',
    order: 1,
    isActive: true
  },
  {
    id: 'content_management',
    name: 'Content Management',
    nameBg: 'Управление на съдържание',
    nameEn: 'Content Management',
    description: 'Permissions related to content management',
    descriptionBg: 'Права, свързани с управлението на съдържание',
    descriptionEn: 'Permissions related to content management',
    icon: 'FileText',
    order: 2,
    isActive: true
  },
  {
    id: 'system_administration',
    name: 'System Administration',
    nameBg: 'Системна администрация',
    nameEn: 'System Administration',
    description: 'Permissions related to system administration',
    descriptionBg: 'Права, свързани със системната администрация',
    descriptionEn: 'Permissions related to system administration',
    icon: 'Settings',
    order: 3,
    isActive: true
  },
  {
    id: 'analytics_reporting',
    name: 'Analytics & Reporting',
    nameBg: 'Анализи и отчети',
    nameEn: 'Analytics & Reporting',
    description: 'Permissions related to analytics and reporting',
    descriptionBg: 'Права, свързани с анализите и отчетите',
    descriptionEn: 'Permissions related to analytics and reporting',
    icon: 'BarChart3',
    order: 4,
    isActive: true
  }
];

// Default permission templates
export const DEFAULT_PERMISSION_TEMPLATES: PermissionTemplate[] = [
  // User Management Permissions
  {
    id: 'users_create',
    categoryId: 'user_management',
    name: 'Create Users',
    nameBg: 'Създаване на потребители',
    nameEn: 'Create Users',
    description: 'Create new users in the system',
    descriptionBg: 'Създаване на нови потребители в системата',
    descriptionEn: 'Create new users in the system',
    resource: 'users',
    action: 'create',
    level: 'write' as const,
    isSystemPermission: true,
    isActive: true,
    order: 1
  },
  {
    id: 'users_read',
    categoryId: 'user_management',
    name: 'View Users',
    nameBg: 'Преглед на потребители',
    nameEn: 'View Users',
    description: 'View user information',
    descriptionBg: 'Преглед на информация за потребители',
    descriptionEn: 'View user information',
    resource: 'users',
    action: 'read',
    level: 'read' as const,
    isSystemPermission: true,
    isActive: true,
    order: 2
  },
  {
    id: 'users_update',
    categoryId: 'user_management',
    name: 'Update Users',
    nameBg: 'Обновяване на потребители',
    nameEn: 'Update Users',
    description: 'Update user information',
    descriptionBg: 'Обновяване на информация за потребители',
    descriptionEn: 'Update user information',
    resource: 'users',
    action: 'update',
    level: 'write' as const,
    isSystemPermission: true,
    isActive: true,
    order: 3
  },
  {
    id: 'users_delete',
    categoryId: 'user_management',
    name: 'Delete Users',
    nameBg: 'Изтриване на потребители',
    nameEn: 'Delete Users',
    description: 'Delete users from the system',
    descriptionBg: 'Изтриване на потребители от системата',
    descriptionEn: 'Delete users from the system',
    resource: 'users',
    action: 'delete',
    level: 'delete' as const,
    isSystemPermission: true,
    isActive: true,
    order: 4
  },
  {
    id: 'users_ban',
    categoryId: 'user_management',
    name: 'Ban Users',
    nameBg: 'Блокиране на потребители',
    nameEn: 'Ban Users',
    description: 'Ban or suspend users',
    descriptionBg: 'Блокиране или спиране на потребители',
    descriptionEn: 'Ban or suspend users',
    resource: 'users',
    action: 'ban',
    level: 'admin' as const,
    isSystemPermission: true,
    isActive: true,
    order: 5
  },
  // Content Management Permissions
  {
    id: 'cars_manage',
    categoryId: 'content_management',
    name: 'Manage Cars',
    nameBg: 'Управление на автомобили',
    nameEn: 'Manage Cars',
    description: 'Manage car listings',
    descriptionBg: 'Управление на обяви за автомобили',
    descriptionEn: 'Manage car listings',
    resource: 'cars',
    action: 'manage',
    level: 'write' as const,
    isSystemPermission: true,
    isActive: true,
    order: 1
  },
  {
    id: 'messages_manage',
    categoryId: 'content_management',
    name: 'Manage Messages',
    nameBg: 'Управление на съобщения',
    nameEn: 'Manage Messages',
    description: 'Manage user messages',
    descriptionBg: 'Управление на потребителски съобщения',
    descriptionEn: 'Manage user messages',
    resource: 'messages',
    action: 'manage',
    level: 'write' as const,
    isSystemPermission: true,
    isActive: true,
    order: 2
  },
  // System Administration Permissions
  {
    id: 'system_settings',
    categoryId: 'system_administration',
    name: 'System Settings',
    nameBg: 'Системни настройки',
    nameEn: 'System Settings',
    description: 'Manage system settings',
    descriptionBg: 'Управление на системните настройки',
    descriptionEn: 'Manage system settings',
    resource: 'system',
    action: 'settings',
    level: 'admin' as const,
    isSystemPermission: true,
    isActive: true,
    order: 1
  },
  {
    id: 'roles_manage',
    categoryId: 'system_administration',
    name: 'Manage Roles',
    nameBg: 'Управление на роли',
    nameEn: 'Manage Roles',
    description: 'Manage user roles and permissions',
    descriptionBg: 'Управление на потребителски роли и права',
    descriptionEn: 'Manage user roles and permissions',
    resource: 'roles',
    action: 'manage',
    level: 'admin' as const,
    isSystemPermission: true,
    isActive: true,
    order: 2
  },
  // Analytics Permissions
  {
    id: 'analytics_view',
    categoryId: 'analytics_reporting',
    name: 'View Analytics',
    nameBg: 'Преглед на анализи',
    nameEn: 'View Analytics',
    description: 'View system analytics',
    descriptionBg: 'Преглед на системни анализи',
    descriptionEn: 'View system analytics',
    resource: 'analytics',
    action: 'view',
    level: 'read' as const,
    isSystemPermission: true,
    isActive: true,
    order: 1
  },
  {
    id: 'reports_generate',
    categoryId: 'analytics_reporting',
    name: 'Generate Reports',
    nameBg: 'Генериране на отчети',
    nameEn: 'Generate Reports',
    description: 'Generate system reports',
    descriptionBg: 'Генериране на системни отчети',
    descriptionEn: 'Generate system reports',
    resource: 'reports',
    action: 'generate',
    level: 'write' as const,
    isSystemPermission: true,
    isActive: true,
    order: 2
  }
];

// Default role templates
export const DEFAULT_ROLE_TEMPLATES: RoleTemplate[] = [
  {
    id: 'super_admin',
    name: 'Super Administrator',
    nameBg: 'Супер администратор',
    nameEn: 'Super Administrator',
    description: 'Full system access with all permissions',
    descriptionBg: 'Пълен достъп до системата с всички права',
    descriptionEn: 'Full system access with all permissions',
    permissions: DEFAULT_PERMISSION_TEMPLATES.map(p => p.id),
    isSystemRole: true,
    isActive: true,
    level: 'super_admin' as const,
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'admin',
    name: 'Administrator',
    nameBg: 'Администратор',
    nameEn: 'Administrator',
    description: 'Administrative access with most permissions',
    descriptionBg: 'Административен достъп с повечето права',
    descriptionEn: 'Administrative access with most permissions',
    permissions: DEFAULT_PERMISSION_TEMPLATES.map(p => p.id),
    isSystemRole: true,
    isActive: true,
    level: 'admin' as const,
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'moderator',
    name: 'Moderator',
    nameBg: 'Модератор',
    nameEn: 'Moderator',
    description: 'Content moderation and user management',
    descriptionBg: 'Модерация на съдържание и управление на потребители',
    descriptionEn: 'Content moderation and user management',
    permissions: DEFAULT_PERMISSION_TEMPLATES.filter(p =>
      p.categoryId === 'user_management' || p.categoryId === 'content_management'
    ).map(p => p.id),
    isSystemRole: true,
    isActive: true,
    level: 'advanced' as const,
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'analyst',
    name: 'Analyst',
    nameBg: 'Аналитик',
    nameEn: 'Analyst',
    description: 'Analytics and reporting access',
    descriptionBg: 'Достъп до анализи и отчети',
    descriptionEn: 'Analytics and reporting access',
    permissions: DEFAULT_PERMISSION_TEMPLATES.filter(p => p.categoryId === 'analytics_reporting').map(p => p.id),
    isSystemRole: true,
    isActive: true,
    level: 'basic' as const,
    createdBy: 'system',
    createdAt: new Date(),
    updatedAt: new Date()
  }
];