import { CarResult, SearchFilters } from './types';

// Generate realistic placeholder images
const carImages = [
    'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1542362567-b07e54358753?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600&h=400&fit=crop',
    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&h=400&fit=crop',
];

export const MOCK_CARS: CarResult[] = [
    {
        id: 'car-001',
        title: 'BMW 320d M Sport',
        subtitle: '2.0 TDI 190 HP Steptronic',
        price: 32500,
        priceFormatted: '€32,500',
        monthlyPrice: '€389/mo',
        year: 2021,
        mileage: 45200,
        mileageFormatted: '45,200 km',
        fuelType: 'diesel',
        transmission: 'automatic',
        horsepower: 190,
        bodyType: 'sedan',
        color: 'black',
        location: 'Sofia',
        dealerName: 'AutoPremium BG',
        imageUrl: carImages[0],
        images: [carImages[0], carImages[1]],
        badges: ['Top Offer'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-10',
        consumption: '5.2 l/100km',
        co2: '132 g/km',
        sellerNumericId: 1001,
        carNumericId: 2001,
    },
    {
        id: 'car-002',
        title: 'Mercedes-Benz C 200',
        subtitle: '1.5 Turbo 204 HP 9G-TRONIC',
        price: 38900,
        priceFormatted: '€38,900',
        monthlyPrice: '€459/mo',
        year: 2022,
        mileage: 28400,
        mileageFormatted: '28,400 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 204,
        bodyType: 'sedan',
        color: 'silver',
        location: 'Plovdiv',
        dealerName: 'Star Motors',
        imageUrl: carImages[1],
        images: [carImages[1], carImages[2]],
        badges: ['Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: true,
        createdAt: '2026-02-08',
        consumption: '6.8 l/100km',
        co2: '153 g/km',
        sellerNumericId: 1002,
        carNumericId: 2002,
    },
    {
        id: 'car-003',
        title: 'Audi A4 Avant 40 TDI',
        subtitle: '2.0 TDI 204 HP S tronic',
        price: 41200,
        priceFormatted: '€41,200',
        monthlyPrice: '€489/mo',
        year: 2023,
        mileage: 12800,
        mileageFormatted: '12,800 km',
        fuelType: 'diesel',
        transmission: 'automatic',
        horsepower: 204,
        bodyType: 'wagon',
        color: 'gray',
        location: 'Varna',
        dealerName: 'Audi Center',
        imageUrl: carImages[2],
        images: [carImages[2], carImages[3]],
        badges: ['Like New', 'Top Offer'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-11',
        consumption: '5.0 l/100km',
        co2: '128 g/km',
        sellerNumericId: 1003,
        carNumericId: 2003,
    },
    {
        id: 'car-004',
        title: 'Volkswagen Golf 8 GTI',
        subtitle: '2.0 TSI 245 HP DSG',
        price: 35700,
        priceFormatted: '€35,700',
        year: 2022,
        mileage: 31500,
        mileageFormatted: '31,500 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 245,
        bodyType: 'hatchback',
        color: 'red',
        location: 'Burgas',
        imageUrl: carImages[3],
        images: [carImages[3], carImages[4]],
        badges: [],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-09',
        consumption: '7.1 l/100km',
        co2: '161 g/km',
        sellerNumericId: 1004,
        carNumericId: 2004,
    },
    {
        id: 'car-005',
        title: 'Toyota RAV4 2.5 Hybrid',
        subtitle: '2.5 Hybrid AWD 222 HP CVT',
        price: 42800,
        priceFormatted: '€42,800',
        monthlyPrice: '€499/mo',
        year: 2023,
        mileage: 8200,
        mileageFormatted: '8,200 km',
        fuelType: 'hybrid',
        transmission: 'automatic',
        horsepower: 222,
        bodyType: 'suv',
        color: 'white',
        location: 'Sofia',
        dealerName: 'Toyota Bulgaria',
        imageUrl: carImages[4],
        images: [carImages[4], carImages[5]],
        badges: ['Like New', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-12',
        consumption: '4.8 l/100km',
        co2: '108 g/km',
        sellerNumericId: 1005,
        carNumericId: 2005,
    },
    {
        id: 'car-006',
        title: 'Tesla Model 3 Long Range',
        subtitle: 'Dual Motor AWD 498 HP',
        price: 39900,
        priceFormatted: '€39,900',
        monthlyPrice: '€469/mo',
        year: 2023,
        mileage: 15600,
        mileageFormatted: '15,600 km',
        fuelType: 'electric',
        transmission: 'automatic',
        horsepower: 498,
        bodyType: 'sedan',
        color: 'white',
        location: 'Sofia',
        dealerName: 'EV Motors BG',
        imageUrl: carImages[5],
        images: [carImages[5], carImages[6]],
        badges: ['Top Offer'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-07',
        consumption: '14.3 kWh/100km',
        co2: '0 g/km',
        sellerNumericId: 1006,
        carNumericId: 2006,
    },
    {
        id: 'car-007',
        title: 'Ford Focus ST',
        subtitle: '2.3 EcoBoost 280 HP 6MT',
        price: 28500,
        priceFormatted: '€28,500',
        year: 2021,
        mileage: 52300,
        mileageFormatted: '52,300 km',
        fuelType: 'petrol',
        transmission: 'manual',
        horsepower: 280,
        bodyType: 'hatchback',
        color: 'blue',
        location: 'Stara Zagora',
        imageUrl: carImages[6],
        images: [carImages[6], carImages[7]],
        badges: [],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-06',
        consumption: '8.0 l/100km',
        co2: '179 g/km',
        sellerNumericId: 1007,
        carNumericId: 2007,
    },
    {
        id: 'car-008',
        title: 'Škoda Octavia Combi',
        subtitle: '2.0 TDI 150 HP DSG',
        price: 24900,
        priceFormatted: '€24,900',
        monthlyPrice: '€289/mo',
        year: 2022,
        mileage: 38700,
        mileageFormatted: '38,700 km',
        fuelType: 'diesel',
        transmission: 'automatic',
        horsepower: 150,
        bodyType: 'wagon',
        color: 'gray',
        location: 'Ruse',
        dealerName: 'Škoda Ruse',
        imageUrl: carImages[7],
        images: [carImages[7], carImages[8]],
        badges: ['Best Price'],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: true,
        createdAt: '2026-02-05',
        consumption: '4.9 l/100km',
        co2: '126 g/km',
        sellerNumericId: 1008,
        carNumericId: 2008,
    },
    {
        id: 'car-009',
        title: 'Volvo XC60 T6 Recharge',
        subtitle: '2.0 T6 PHEV 350 HP AWD',
        price: 54700,
        priceFormatted: '€54,700',
        monthlyPrice: '€639/mo',
        year: 2023,
        mileage: 5400,
        mileageFormatted: '5,400 km',
        fuelType: 'hybrid',
        transmission: 'automatic',
        horsepower: 350,
        bodyType: 'suv',
        color: 'black',
        location: 'Sofia',
        dealerName: 'Volvo Sofia',
        imageUrl: carImages[8],
        images: [carImages[8], carImages[9]],
        badges: ['Like New', 'Top Offer', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-11',
        consumption: '2.1 l/100km',
        co2: '47 g/km',
        sellerNumericId: 1009,
        carNumericId: 2009,
    },
    {
        id: 'car-010',
        title: 'Hyundai Tucson 1.6 T-GDi',
        subtitle: '1.6 T-GDi 180 HP DCT',
        price: 31200,
        priceFormatted: '€31,200',
        monthlyPrice: '€369/mo',
        year: 2022,
        mileage: 24100,
        mileageFormatted: '24,100 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 180,
        bodyType: 'suv',
        color: 'green',
        location: 'Plovdiv',
        imageUrl: carImages[9],
        images: [carImages[9], carImages[10]],
        badges: ['Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-04',
        consumption: '7.5 l/100km',
        co2: '169 g/km',
        sellerNumericId: 1010,
        carNumericId: 2010,
    },
    {
        id: 'car-011',
        title: 'Porsche Cayenne S',
        subtitle: '2.9 V6 Twin-Turbo 440 HP',
        price: 78500,
        priceFormatted: '€78,500',
        monthlyPrice: '€929/mo',
        year: 2022,
        mileage: 19800,
        mileageFormatted: '19,800 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 440,
        bodyType: 'suv',
        color: 'white',
        location: 'Sofia',
        dealerName: 'Porsche Center Sofia',
        imageUrl: carImages[10],
        images: [carImages[10], carImages[11]],
        badges: ['Premium', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-10',
        consumption: '10.8 l/100km',
        co2: '244 g/km',
        sellerNumericId: 1011,
        carNumericId: 2011,
    },
    {
        id: 'car-012',
        title: 'Renault Clio TCe 100',
        subtitle: '1.0 TCe 100 HP 5MT',
        price: 14500,
        priceFormatted: '€14,500',
        monthlyPrice: '€169/mo',
        year: 2021,
        mileage: 41200,
        mileageFormatted: '41,200 km',
        fuelType: 'petrol',
        transmission: 'manual',
        horsepower: 100,
        bodyType: 'hatchback',
        color: 'orange',
        location: 'Varna',
        imageUrl: carImages[11],
        images: [carImages[11], carImages[0]],
        badges: ['Best Price'],
        condition: 'good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-03',
        consumption: '5.2 l/100km',
        co2: '118 g/km',
        sellerNumericId: 1012,
        carNumericId: 2012,
    },
    {
        id: 'car-013',
        title: 'Kia Sportage 1.6 T-GDi',
        subtitle: '1.6 T-GDi HEV 230 HP DCT AWD',
        price: 36900,
        priceFormatted: '€36,900',
        monthlyPrice: '€429/mo',
        year: 2023,
        mileage: 11500,
        mileageFormatted: '11,500 km',
        fuelType: 'hybrid',
        transmission: 'automatic',
        horsepower: 230,
        bodyType: 'suv',
        color: 'gray',
        location: 'Sofia',
        dealerName: 'Kia Motors BG',
        imageUrl: carImages[0],
        images: [carImages[0], carImages[3]],
        badges: ['Like New'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-09',
        consumption: '5.4 l/100km',
        co2: '122 g/km',
        sellerNumericId: 1013,
        carNumericId: 2013,
    },
    {
        id: 'car-014',
        title: 'Opel Corsa-e Electric',
        subtitle: '100 kW 136 HP 50 kWh',
        price: 26200,
        priceFormatted: '€26,200',
        monthlyPrice: '€309/mo',
        year: 2022,
        mileage: 22300,
        mileageFormatted: '22,300 km',
        fuelType: 'electric',
        transmission: 'automatic',
        horsepower: 136,
        bodyType: 'hatchback',
        color: 'green',
        location: 'Burgas',
        imageUrl: carImages[1],
        images: [carImages[1], carImages[4]],
        badges: ['Eco'],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-07',
        consumption: '16.5 kWh/100km',
        co2: '0 g/km',
        sellerNumericId: 1014,
        carNumericId: 2014,
    },
    {
        id: 'car-015',
        title: 'Mazda CX-5 2.5 Skyactiv',
        subtitle: '2.5 Skyactiv-G 194 HP 6AT AWD',
        price: 33400,
        priceFormatted: '€33,400',
        monthlyPrice: '€399/mo',
        year: 2022,
        mileage: 27800,
        mileageFormatted: '27,800 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 194,
        bodyType: 'suv',
        color: 'red',
        location: 'Plovdiv',
        dealerName: 'Mazda Plovdiv',
        imageUrl: carImages[2],
        images: [carImages[2], carImages[5]],
        badges: ['Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-06',
        consumption: '7.8 l/100km',
        co2: '177 g/km',
        sellerNumericId: 1015,
        carNumericId: 2015,
    },
    {
        id: 'car-016',
        title: 'Peugeot 3008 GT',
        subtitle: '1.6 PureTech 180 HP EAT8',
        price: 29800,
        priceFormatted: '€29,800',
        monthlyPrice: '€349/mo',
        year: 2021,
        mileage: 47200,
        mileageFormatted: '47,200 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 180,
        bodyType: 'suv',
        color: 'blue',
        location: 'Stara Zagora',
        imageUrl: carImages[3],
        images: [carImages[3], carImages[6]],
        badges: [],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-05',
        consumption: '6.5 l/100km',
        co2: '147 g/km',
        sellerNumericId: 1016,
        carNumericId: 2016,
    },
    {
        id: 'car-017',
        title: 'Nissan Qashqai e-POWER',
        subtitle: '1.5 e-POWER 190 HP CVT',
        price: 34100,
        priceFormatted: '€34,100',
        monthlyPrice: '€399/mo',
        year: 2023,
        mileage: 9800,
        mileageFormatted: '9,800 km',
        fuelType: 'hybrid',
        transmission: 'automatic',
        horsepower: 190,
        bodyType: 'crossover',
        color: 'black',
        location: 'Varna',
        dealerName: 'Nissan Varna',
        imageUrl: carImages[4],
        images: [carImages[4], carImages[7]],
        badges: ['Like New', 'Top Offer'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-11',
        consumption: '5.3 l/100km',
        co2: '119 g/km',
        sellerNumericId: 1017,
        carNumericId: 2017,
    },
    {
        id: 'car-018',
        title: 'Honda Civic Type R',
        subtitle: '2.0 VTEC Turbo 329 HP 6MT',
        price: 48900,
        priceFormatted: '€48,900',
        year: 2023,
        mileage: 6200,
        mileageFormatted: '6,200 km',
        fuelType: 'petrol',
        transmission: 'manual',
        horsepower: 329,
        bodyType: 'hatchback',
        color: 'white',
        location: 'Sofia',
        imageUrl: carImages[5],
        images: [carImages[5], carImages[8]],
        badges: ['Like New', 'Premium'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-10',
        consumption: '8.2 l/100km',
        co2: '186 g/km',
        sellerNumericId: 1018,
        carNumericId: 2018,
    },
    {
        id: 'car-019',
        title: 'SEAT Leon FR 1.5 TSI',
        subtitle: '1.5 TSI 150 HP DSG',
        price: 22800,
        priceFormatted: '€22,800',
        monthlyPrice: '€269/mo',
        year: 2021,
        mileage: 56200,
        mileageFormatted: '56,200 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 150,
        bodyType: 'hatchback',
        color: 'red',
        location: 'Ruse',
        imageUrl: carImages[6],
        images: [carImages[6], carImages[9]],
        badges: [],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-04',
        consumption: '5.9 l/100km',
        co2: '133 g/km',
        sellerNumericId: 1019,
        carNumericId: 2019,
    },
    {
        id: 'car-020',
        title: 'BMW X5 xDrive40d',
        subtitle: '3.0 d 340 HP Steptronic',
        price: 68200,
        priceFormatted: '€68,200',
        monthlyPrice: '€799/mo',
        year: 2023,
        mileage: 14500,
        mileageFormatted: '14,500 km',
        fuelType: 'diesel',
        transmission: 'automatic',
        horsepower: 340,
        bodyType: 'suv',
        color: 'black',
        location: 'Sofia',
        dealerName: 'AutoPremium BG',
        imageUrl: carImages[7],
        images: [carImages[7], carImages[10]],
        badges: ['Top Offer', 'Premium', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-12',
        consumption: '7.2 l/100km',
        co2: '188 g/km',
        sellerNumericId: 1020,
        carNumericId: 2020,
    },
    {
        id: 'car-021',
        title: 'Dacia Duster 1.5 dCi',
        subtitle: '1.5 Blue dCi 115 HP 6MT 4x4',
        price: 19500,
        priceFormatted: '€19,500',
        monthlyPrice: '€229/mo',
        year: 2022,
        mileage: 35600,
        mileageFormatted: '35,600 km',
        fuelType: 'diesel',
        transmission: 'manual',
        horsepower: 115,
        bodyType: 'suv',
        color: 'brown',
        location: 'Pleven',
        imageUrl: carImages[8],
        images: [carImages[8], carImages[11]],
        badges: ['Best Price'],
        condition: 'very_good',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-03',
        consumption: '5.7 l/100km',
        co2: '149 g/km',
        sellerNumericId: 1021,
        carNumericId: 2021,
    },
    {
        id: 'car-022',
        title: 'Mercedes-Benz GLC 300 d',
        subtitle: '2.0 d 269 HP 9G-TRONIC 4MATIC',
        price: 56800,
        priceFormatted: '€56,800',
        monthlyPrice: '€669/mo',
        year: 2023,
        mileage: 11200,
        mileageFormatted: '11,200 km',
        fuelType: 'diesel',
        transmission: 'automatic',
        horsepower: 269,
        bodyType: 'suv',
        color: 'silver',
        location: 'Sofia',
        dealerName: 'Star Motors',
        imageUrl: carImages[9],
        images: [carImages[9], carImages[0]],
        badges: ['Like New', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: true,
        isFavorited: false,
        createdAt: '2026-02-11',
        consumption: '6.4 l/100km',
        co2: '168 g/km',
        sellerNumericId: 1022,
        carNumericId: 2022,
    },
    {
        id: 'car-023',
        title: 'Fiat 500e La Prima',
        subtitle: '42 kWh 118 HP',
        price: 23400,
        priceFormatted: '€23,400',
        monthlyPrice: '€279/mo',
        year: 2022,
        mileage: 18500,
        mileageFormatted: '18,500 km',
        fuelType: 'electric',
        transmission: 'automatic',
        horsepower: 118,
        bodyType: 'hatchback',
        color: 'green',
        location: 'Plovdiv',
        imageUrl: carImages[10],
        images: [carImages[10], carImages[1]],
        badges: ['Eco', 'Verified'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-08',
        consumption: '14.0 kWh/100km',
        co2: '0 g/km',
        sellerNumericId: 1023,
        carNumericId: 2023,
    },
    {
        id: 'car-024',
        title: 'Alfa Romeo Giulia Veloce',
        subtitle: '2.0 Turbo 280 HP 8AT',
        price: 44600,
        priceFormatted: '€44,600',
        year: 2022,
        mileage: 21700,
        mileageFormatted: '21,700 km',
        fuelType: 'petrol',
        transmission: 'automatic',
        horsepower: 280,
        bodyType: 'sedan',
        color: 'red',
        location: 'Sofia',
        imageUrl: carImages[11],
        images: [carImages[11], carImages[2]],
        badges: ['Premium'],
        condition: 'excellent',
        isNew: false,
        isTopOffer: false,
        isFavorited: false,
        createdAt: '2026-02-06',
        consumption: '7.6 l/100km',
        co2: '172 g/km',
        sellerNumericId: 1024,
        carNumericId: 2024,
    },
];

export const FEATURE_OPTIONS = [
    { value: 'navigation', label: 'Navigation System' },
    { value: 'sunroof', label: 'Sunroof / Panoramic Roof' },
    { value: 'leather', label: 'Leather Interior' },
    { value: 'heated_seats', label: 'Heated Seats' },
    { value: 'parking_sensors', label: 'Parking Sensors' },
    { value: 'backup_camera', label: 'Backup Camera' },
    { value: 'cruise_control', label: 'Adaptive Cruise Control' },
    { value: 'blind_spot', label: 'Blind Spot Monitor' },
    { value: 'lane_assist', label: 'Lane Keep Assist' },
    { value: 'apple_carplay', label: 'Apple CarPlay' },
    { value: 'android_auto', label: 'Android Auto' },
    { value: 'keyless', label: 'Keyless Entry & Start' },
    { value: 'led_lights', label: 'LED Headlights' },
    { value: 'climate_control', label: 'Climate Control' },
    { value: 'alloy_wheels', label: 'Alloy Wheels' },
    { value: 'sport_package', label: 'Sport Package' },
    { value: 'tow_bar', label: 'Tow Bar' },
    { value: 'roof_rack', label: 'Roof Rack' },
];

export const DEFAULT_FILTERS: SearchFilters = {
    make: '',
    model: '',
    priceMin: '',
    priceMax: '',
    yearFrom: '',
    yearTo: '',
    mileageMax: '',
    fuelType: '',
    transmission: '',
    bodyType: '',
    condition: '',
    color: '',
    locationRadius: '',
    features: [],
    sellerType: '',
    sortBy: 'relevance',
};

export function filterAndSortCars(
    cars: CarResult[],
    filters: SearchFilters
): CarResult[] {
    let results = [...cars];

    if (filters.make) {
        results = results.filter((c) =>
            c.title.toLowerCase().includes(filters.make.toLowerCase())
        );
    }
    if (filters.model) {
        results = results.filter((c) =>
            c.title.toLowerCase().includes(filters.model.toLowerCase()) ||
            c.subtitle.toLowerCase().includes(filters.model.toLowerCase())
        );
    }
    if (filters.priceMin) {
        results = results.filter((c) => c.price >= parseInt(filters.priceMin));
    }
    if (filters.priceMax) {
        results = results.filter((c) => c.price <= parseInt(filters.priceMax));
    }
    if (filters.yearFrom) {
        results = results.filter((c) => c.year >= parseInt(filters.yearFrom));
    }
    if (filters.yearTo) {
        results = results.filter((c) => c.year <= parseInt(filters.yearTo));
    }
    if (filters.mileageMax) {
        results = results.filter((c) => c.mileage <= parseInt(filters.mileageMax));
    }
    if (filters.fuelType) {
        results = results.filter((c) => c.fuelType === filters.fuelType);
    }
    if (filters.transmission) {
        results = results.filter((c) => c.transmission === filters.transmission);
    }
    if (filters.bodyType) {
        results = results.filter((c) => c.bodyType === filters.bodyType);
    }
    if (filters.condition) {
        results = results.filter((c) => c.condition === filters.condition);
    }
    if (filters.color) {
        results = results.filter((c) => c.color === filters.color);
    }
    if (filters.sellerType === 'dealer') {
        results = results.filter((c) => !!c.dealerName);
    } else if (filters.sellerType === 'private') {
        results = results.filter((c) => !c.dealerName);
    }

    // Sort
    switch (filters.sortBy) {
        case 'price_asc':
            results.sort((a, b) => a.price - b.price);
            break;
        case 'price_desc':
            results.sort((a, b) => b.price - a.price);
            break;
        case 'newest':
            results.sort(
                (a, b) =>
                    new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
            );
            break;
        case 'year_desc':
            results.sort((a, b) => b.year - a.year);
            break;
        case 'year_asc':
            results.sort((a, b) => a.year - b.year);
            break;
        case 'mileage_asc':
            results.sort((a, b) => a.mileage - b.mileage);
            break;
        case 'mileage_desc':
            results.sort((a, b) => b.mileage - a.mileage);
            break;
        default:
            // relevance — top offers first, then newest
            results.sort((a, b) => {
                if (a.isTopOffer && !b.isTopOffer) return -1;
                if (!a.isTopOffer && b.isTopOffer) return 1;
                return (
                    new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
                );
            });
    }

    return results;
}
