const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

// تحويل الصور الكبيرة إلى WebP
class WebPConverter {
  constructor(sourceDir, minSizeMB = 0.5) {
    this.sourceDir = sourceDir;
    this.minSize = minSizeMB * 1024 * 1024; // Convert to bytes
    this.converted = [];
    this.errors = [];
  }

  // العثور على الصور الكبيرة
  async findLargeImages(dir = this.sourceDir, images = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!['node_modules', 'build', '.git'].includes(entry.name)) {
          await this.findLargeImages(fullPath, images);
        }
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (['.jpg', '.jpeg', '.png'].includes(ext)) {
          const stats = fs.statSync(fullPath);
          if (stats.size >= this.minSize) {
            images.push({
              path: fullPath,
              name: entry.name,
              size: stats.size,
              sizeMB: (stats.size / (1024 * 1024)).toFixed(2)
            });
          }
        }
      }
    }

    return images;
  }

  // تحويل صورة واحدة إلى WebP
  async convertImage(imagePath, quality = 85) {
    try {
      const parsed = path.parse(imagePath);
      const webpPath = path.join(parsed.dir, `${parsed.name}.webp`);

      // Skip if WebP already exists
      if (fs.existsSync(webpPath)) {
        console.log(`⏭️  Skipping ${parsed.name} (WebP exists)`);
        return null;
      }

      const originalSize = fs.statSync(imagePath).size;

      await sharp(imagePath)
        .webp({ quality: quality, effort: 6 })
        .toFile(webpPath);

      const newSize = fs.statSync(webpPath).size;
      const savings = ((1 - newSize / originalSize) * 100).toFixed(1);

      const result = {
        original: imagePath,
        webp: webpPath,
        originalSizeMB: (originalSize / (1024 * 1024)).toFixed(2),
        webpSizeMB: (newSize / (1024 * 1024)).toFixed(2),
        savings: `${savings}%`
      };

      this.converted.push(result);
      console.log(`✅ Converted: ${parsed.name} (${result.originalSizeMB}MB → ${result.webpSizeMB}MB, -${savings}%)`);
      
      return result;
    } catch (error) {
      const errorInfo = {
        path: imagePath,
        error: error.message
      };
      this.errors.push(errorInfo);
      console.error(`❌ Error converting ${imagePath}: ${error.message}`);
      return null;
    }
  }

  // تحويل جميع الصور الكبيرة
  async convertAll(quality = 85) {
    console.log('🔍 Finding large images...');
    const largeImages = await this.findLargeImages();
    
    console.log(`📊 Found ${largeImages.length} images ≥ ${this.minSize / (1024 * 1024)}MB`);
    console.log('🔄 Starting conversion...\n');

    for (const image of largeImages) {
      await this.convertImage(image.path, quality);
    }

    return this.generateReport();
  }

  // إنشاء تقرير
  generateReport() {
    const totalOriginal = this.converted.reduce((sum, c) => sum + parseFloat(c.originalSizeMB), 0);
    const totalWebP = this.converted.reduce((sum, c) => sum + parseFloat(c.webpSizeMB), 0);
    const totalSavings = totalOriginal - totalWebP;
    const savingsPercent = ((totalSavings / totalOriginal) * 100).toFixed(1);

    return {
      summary: {
        totalConverted: this.converted.length,
        totalErrors: this.errors.length,
        originalSizeMB: totalOriginal.toFixed(2),
        webpSizeMB: totalWebP.toFixed(2),
        savedMB: totalSavings.toFixed(2),
        savingsPercent: `${savingsPercent}%`
      },
      converted: this.converted,
      errors: this.errors
    };
  }

  // حفظ التقرير
  saveReport(outputPath) {
    const report = this.generateReport();
    
    const reportContent = `# 🖼️ WebP Conversion Report
Generated: ${new Date().toLocaleString('ar-BG')}

## 📈 Summary
- **Images Converted:** ${report.summary.totalConverted}
- **Conversion Errors:** ${report.summary.totalErrors}
- **Original Size:** ${report.summary.originalSizeMB} MB
- **WebP Size:** ${report.summary.webpSizeMB} MB
- **Space Saved:** ${report.summary.savedMB} MB (${report.summary.savingsPercent})

## ✅ Converted Images
${report.converted.map((c, i) => {
  const name = path.basename(c.original);
  return `${i + 1}. **${name}**
   - Original: ${c.originalSizeMB} MB
   - WebP: ${c.webpSizeMB} MB
   - Savings: ${c.savings}
   - Path: \`${path.relative(this.sourceDir, c.webp)}\``;
}).join('\n\n')}

${report.errors.length > 0 ? `## ❌ Conversion Errors
${report.errors.map((e, i) => `${i + 1}. ${path.basename(e.path)}: ${e.error}`).join('\n')}` : ''}

---
*Generated by WebP Converter for Koli One*
`;

    fs.writeFileSync(outputPath, reportContent);
    fs.writeFileSync(outputPath.replace('.md', '.json'), JSON.stringify(report, null, 2));
    
    console.log(`\n✅ Report saved to: ${outputPath}`);
    return report;
  }
}

// تشغيل التحويل
async function main() {
  const rootDir = path.join(__dirname, '..');
  const converter = new WebPConverter(rootDir, 0.5); // تحويل الصور ≥ 0.5 MB

  try {
    await converter.convertAll(85); // جودة 85%
    
    const reportPath = path.join(__dirname, '../WEEK2_DAY3_WEBP_CONVERSION.md');
    const report = converter.saveReport(reportPath);

    console.log('\n✅ WebP conversion complete!');
    console.log(`📄 Report: ${reportPath}`);
    console.log(`\n📊 Results:`);
    console.log(`   Converted: ${report.summary.totalConverted} images`);
    console.log(`   Original: ${report.summary.originalSizeMB} MB`);
    console.log(`   WebP: ${report.summary.webpSizeMB} MB`);
    console.log(`   Saved: ${report.summary.savedMB} MB (${report.summary.savingsPercent})`);
    
    if (report.summary.totalErrors > 0) {
      console.log(`\n⚠️  Errors: ${report.summary.totalErrors} images failed to convert`);
    }
  } catch (error) {
    console.error('❌ Fatal error:', error);
    process.exit(1);
  }
}

main().catch(console.error);
