const fs = require('fs');
const path = require('path');

// حذف ملفات WebP الأكبر من الأصل
class WebPOptimizer {
  constructor(rootDir) {
    this.rootDir = rootDir;
    this.deleted = [];
    this.kept = [];
  }

  // فحص جميع ملفات WebP
  async findWebPFiles(dir = this.rootDir, files = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        if (!['node_modules', 'build', '.git'].includes(entry.name)) {
          await this.findWebPFiles(fullPath, files);
        }
      } else if (entry.isFile() && entry.name.endsWith('.webp')) {
        const parsed = path.parse(fullPath);
        
        // البحث عن الأصل (jpg, jpeg, png)
        let originalPath = null;
        for (const ext of ['.jpg', '.jpeg', '.png']) {
          const testPath = path.join(parsed.dir, parsed.name + ext);
          if (fs.existsSync(testPath)) {
            originalPath = testPath;
            break;
          }
        }

        if (originalPath) {
          const webpSize = fs.statSync(fullPath).size;
          const originalSize = fs.statSync(originalPath).size;
          
          files.push({
            webp: fullPath,
            original: originalPath,
            webpSize: webpSize,
            originalSize: originalSize,
            webpSizeMB: (webpSize / (1024 * 1024)).toFixed(2),
            originalSizeMB: (originalSize / (1024 * 1024)).toFixed(2),
            savings: ((1 - webpSize / originalSize) * 100).toFixed(1)
          });
        }
      }
    }

    return files;
  }

  // حذف WebP الأكبر
  async optimizeWebP() {
    console.log('🔍 Finding WebP files...');
    const webpFiles = await this.findWebPFiles();
    
    console.log(`📊 Found ${webpFiles.length} WebP files with originals`);
    console.log('🔄 Optimizing...\n');

    for (const file of webpFiles) {
      const savings = parseFloat(file.savings);
      
      if (savings < 0) {
        // WebP أكبر من الأصل - احذف WebP
        fs.unlinkSync(file.webp);
        this.deleted.push({
          ...file,
          reason: `WebP larger by ${Math.abs(savings).toFixed(1)}%`
        });
        console.log(`❌ Deleted: ${path.basename(file.webp)} (${file.webpSizeMB}MB > ${file.originalSizeMB}MB)`);
      } else {
        // WebP أصغر - اترك
        this.kept.push(file);
        console.log(`✅ Kept: ${path.basename(file.webp)} (${file.webpSizeMB}MB < ${file.originalSizeMB}MB, -${savings}%)`);
      }
    }

    return this.generateReport();
  }

  // إنشاء تقرير
  generateReport() {
    const totalDeletedSize = this.deleted.reduce((sum, f) => sum + f.webpSize, 0);
    const totalKeptWebP = this.kept.reduce((sum, f) => sum + f.webpSize, 0);
    const totalKeptOriginal = this.kept.reduce((sum, f) => sum + f.originalSize, 0);
    const actualSavings = totalKeptOriginal - totalKeptWebP;

    return {
      summary: {
        totalWebPFiles: this.deleted.length + this.kept.length,
        deletedWebP: this.deleted.length,
        keptWebP: this.kept.length,
        deletedSizeMB: (totalDeletedSize / (1024 * 1024)).toFixed(2),
        actualSavingsMB: (actualSavings / (1024 * 1024)).toFixed(2),
        savingsPercent: ((actualSavings / totalKeptOriginal) * 100).toFixed(1)
      },
      deleted: this.deleted,
      kept: this.kept
    };
  }

  // حفظ التقرير
  saveReport(outputPath) {
    const report = this.generateReport();
    
    const reportContent = `# 🗑️ WebP Optimization Report
Generated: ${new Date().toLocaleString('ar-BG')}

## 📈 Summary
- **Total WebP Files:** ${report.summary.totalWebPFiles}
- **Deleted (larger than original):** ${report.summary.deletedWebP}
- **Kept (smaller than original):** ${report.summary.keptWebP}
- **Space Freed:** ${report.summary.deletedSizeMB} MB (from deleting inefficient WebP)
- **Actual Savings:** ${report.summary.actualSavingsMB} MB (${report.summary.savingsPercent}%)

## ❌ Deleted WebP Files (Larger than Original)
${report.deleted.map((f, i) => `${i + 1}. **${path.basename(f.webp)}**
   - WebP: ${f.webpSizeMB} MB
   - Original: ${f.originalSizeMB} MB
   - Reason: ${f.reason}`).join('\n\n')}

## ✅ Kept WebP Files (Smaller than Original)
Top 10 best savings:
${report.kept
  .sort((a, b) => parseFloat(b.savings) - parseFloat(a.savings))
  .slice(0, 10)
  .map((f, i) => `${i + 1}. **${path.basename(f.webp)}** (${f.originalSizeMB}MB → ${f.webpSizeMB}MB, -${f.savings}%)`).join('\n')}

---
*Generated by WebP Optimizer for Bulgarian Car Marketplace*
`;

    fs.writeFileSync(outputPath, reportContent);
    fs.writeFileSync(outputPath.replace('.md', '.json'), JSON.stringify(report, null, 2));
    
    console.log(`\n✅ Report saved to: ${outputPath}`);
    return report;
  }
}

// تشغيل التحسين
async function main() {
  const rootDir = path.join(__dirname, '..');
  const optimizer = new WebPOptimizer(rootDir);

  try {
    await optimizer.optimizeWebP();
    
    const reportPath = path.join(__dirname, '../WEEK2_DAY3_WEBP_OPTIMIZATION.md');
    const report = optimizer.saveReport(reportPath);

    console.log('\n✅ WebP optimization complete!');
    console.log(`📄 Report: ${reportPath}`);
    console.log(`\n📊 Results:`);
    console.log(`   Deleted: ${report.summary.deletedWebP} inefficient WebP files`);
    console.log(`   Kept: ${report.summary.keptWebP} efficient WebP files`);
    console.log(`   Freed: ${report.summary.deletedSizeMB} MB`);
    console.log(`   Savings: ${report.summary.actualSavingsMB} MB (${report.summary.savingsPercent}%)`);
  } catch (error) {
    console.error('❌ Fatal error:', error);
    process.exit(1);
  }
}

main().catch(console.error);
